config/routes.rb
Rails.application.routes.draw do
  resources :repositories do
    resources :jobs
  end
  resources :jobs do
    resource :log
    resources :matches
  end

  root 'repositories#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compiler_error_match.rb
class CompilerErrorMatch < ApplicationRecord
    belongs_to :java_repo_build_datum
end

app/models/compiler_error_mysql_match.rb
class CompilerErrorMysqlMatch < ActiveRecord::Base
    belongs_to :java_repo_job_datum
  end

app/models/java_repo_build_datum.rb
class JavaRepoBuildDatum < ActiveRecord::Base
  belongs_to :travis_java_repository
  has_many :compiler_error_match
end

app/models/java_repo_job_datum.rb
class JavaRepoJobDatum < ActiveRecord::Base
  belongs_to :travis_java_repository
  has_many :compiler_error_mysql_matches
end

app/models/travis_java_repository.rb
class TravisJavaRepository < ActiveRecord::Base
  has_many :java_repo_job_data
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    def index
        @repo = TravisJavaRepository.find(params[:repository_id])
        sift = params[:sift]
        branch = params[:branch]
        search_text = params[:search_text]
        if sift
            @jobs = @repo.java_repo_job_data.where("has_compiler_error = ?", 1).paginate(:page => params[:page], :per_page => 30).order('job_id')
        elsif branch
            @jobs = @repo.java_repo_job_data.where("build_branch = ?", branch).paginate(:page => params[:page], :per_page => 30).order('job_id')
        elsif search_text
            @jobs = @repo.java_repo_job_data.where("job_number = ?", search_text).paginate(:page => params[:page], :per_page => 30).order('job_id')
        else
            @jobs = @repo.java_repo_job_data.paginate(:page => params[:page], :per_page => 30).order('job_id')
        end

    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController
    def show
        @job = JavaRepoJobDatum.find(params[:job_id])
        repo_name = @job.repo_name
        job_number = @job.job_number
        @slice_segment = @job.slice_segment.lines
        #render json: @job , type: 'text/plain; charset=utf-8', disposition: 'inline'
        @log_file = IO.readlines "/home/fdse/user/zc/bodyLog2/build_logs/#{repo_name.sub(/\//, '@')}/#{job_number.sub(/\./, '@')}.log"
    end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
    def index
        @job = JavaRepoJobDatum.find(params[:job_id])
        repo_name = @job.repo_name
        job_number = @job.job_number
        @slice_segment = @job.slice_segment.lines
        @log_file = IO.readlines "/home/fdse/user/zc/bodyLog2/build_logs/#{repo_name.sub(/\//, '@')}/#{job_number.sub(/\./, '@')}.log"
        @matches = @job.compiler_error_mysql_matches
    end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index    
    @builds = params[:builds] || 50
    @stars = params[:stars] || 25
    @search_text = params[:search_text]
    if @search_text
      @repo = TravisJavaRepository.where("(repo_name LIKE ? OR id = ?) AND id >= ? AND builds > ? AND stars>?", '%' + @search_text + '%', @search_text, 1,  @builds.to_i, @stars.to_i).paginate(:page => params[:page], :per_page => 30).order('id')
    else
      @repo = TravisJavaRepository.where("id >= ? AND builds > ? AND stars>?", 1, @builds.to_i, @stars.to_i).paginate(:page => params[:page], :per_page => 30).order('id')
    end       
  end
end

app/controllers/repository_controller.rb
class RepositoryController < ApplicationController
  def index
    @builds = params[:builds] || 50
    @stars = params[:stars] || 25
    @repo_name = params[:repo_name]
    if @repo_name
      @repo = TravisJavaRepository.where("repo_name LIKE ? AND id >= ? AND builds > ? AND stars>?", '%' + @repo_name + '%', 1,  @builds.to_i, @stars.to_i).paginate(:page => params[:page], :per_page => 30).order('id')
    else
      @repo = TravisJavaRepository.where("id >= ? AND builds > ? AND stars>?", 1, @builds.to_i, @stars.to_i).paginate(:page => params[:page], :per_page => 30).order('id')
    end

  end

  def jobs
    repo = TravisJavaRepository.find(params[:repo_id])
    branch = params[:branch]
    if branch
      @jobs = repo.java_repo_build_data.where("build_branch = ?", branch).paginate(:page => params[:page], :per_page => 100).order('job_id')
    else
      @jobs = repo.java_repo_build_data.paginate(:page => params[:page], :per_page => 100).order('job_id')
    end

  end

  def log
    send_file "/home/fdse/user/zc/bodyLog2/build_logs/#{params[:repo].sub(/\//, '@')}/#{params[:job_number].sub(/\./, '@')}.log", type: 'text/plain; charset=utf-8', disposition: 'inline'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
    def compare_url(url, repo_name)
        rs = '/compare'  + '.+'
        r = Regexp.new rs
        m = r.match url
        return m[0] if m
        rs = '/pull'  + '.+'
        r = Regexp.new rs
        m = r.match url
        return m[0] if m
        rs = '/commit'  + '.+'
        r = Regexp.new rs
        m = r.match url
        return m[0] if m
    end
end

app/helpers/log_helper.rb
module LogHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/repository_helper.rb
module RepositoryHelper
end

app/views/jobs/index.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <a class="navbar-brand" href="#">  
    <%= image_tag("travis.png", size: "90x30") %>
  </a>
  <div class="collapse navbar-collapse">
    <div class="navbar-nav">
      <%= link_to 'Home', repositories_path, class: "nav-item nav-link active" %>
      <%= link_to  @repo.repo_name, repository_jobs_path(repository_id: @repo.id, sift: true), :target => "_blank", class: "nav-item nav-link" %>
    </div>
  </div>
  <%= form_tag(repository_jobs_path(@repo), method: "get", class: 'form-inline') do %>
    <%= search_field_tag :search_text, nil, {class: 'form-control mr-sm-2', placeholder: "Job number/branch", 'aria-label': "Search"} %>
    <%= button_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
  <% end %>
</nav>

<div class="container">
  <% @jobs.each do |job| %>
    <div class="row border rounded my-2 py-2  <%= job.has_compiler_error == 1 ? "border-warning bg-info text-white" : "border-info bg-light" %>">
      <% link_color = job.has_compiler_error == 1 ? "text-light" : "text-dark" %>
      <div class="col-1">
        <%= job.job_number %>
      </div>
      <div class="col-1">
        <%= job.job_state %>
      </div>
      <div class="col-2">
        <%= link_to job.build_branch, repository_jobs_path(repository_id: job.travis_java_repository_id, branch: job.build_branch), :target => "_blank", class: link_color %>
      </div>
      <div class="col-4">
        <%= link_to compare_url(job.commit_compare_url, job.repo_name),  job.commit_compare_url %>
      </div>
      <div class="col-1">
        <%= link_to 'match', job_matches_path(job), :target => "_blank", class: link_color %>
      </div>
      <div class="col-3 commit-message ellipis" data-container="body" data-toggle="popover" data-placement="bottom">
        <%= job.commit_message %>
      </div>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-auto">
      <%= will_paginate @jobs %> 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CILink</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <%= yield %>
  </body>
</html>

app/views/logs/index.html.erb
<p>
    <%= @slice_segment %>
</p>

app/views/logs/show.html.erb
<code>
    <% @slice_segment.each do |line| %>
        <%= line %><br>
    <% end %>
</code>

<code>
    <% @log_file.each do |line| %>
        <%= line %><br>
    <% end %>
</code>

app/views/matches/index.html.erb
<ul class="nav nav-tabs fixed-top bg-light" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="log-tab" data-toggle="tab" href="#log" role="tab" aria-controls="log" aria-selected="true">Log</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="slice-tab" data-toggle="tab" href="#slice" role="tab" aria-controls="slice" aria-selected="false">Slice</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="match-tab" data-toggle="tab" href="#match" role="tab" aria-controls="match" aria-selected="false">Match</a>
  </li>
</ul>

<div class="tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="log" role="tabpanel" aria-labelledby="log-tab">
    <code>
      <% @log_file.each do |line| %>
          <%= line %><br>
      <% end %>
    </code>
  </div>

  <div class="tab-pane fade" id="slice" role="tabpanel" aria-labelledby="slice-tab">
    <code>
      <% @slice_segment.each do |line| %>
          <%= line %><br>
      <% end %>
    </code>
  </div>

  <div class="tab-pane fade" id="match" role="tabpanel" aria-labelledby="cmatch-tab">
    <% @matches.each do |match| %>
      <div class="container rounded bg-info my-5 pt-3 pb-1 px-3">
        <div class="row border rounded my-2 py-2  border-info bg-white">
          <div class="col-1">
            Order <%= match.order_number %>
          </div>
          <div class="col-2">
            Similarity <%= match.similarity %>
          </div>
          <div class="col-8">
            <%= match.regex_value %>
          </div>
        </div>
        <div class="row border rounded my-2 py-2  border-info bg-light">
          <div class="col-12">
            <% match.segment.lines.each do |line| %>
              <%= line %><br>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/repositories/index.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <a class="navbar-brand" href="#">  
    <%= image_tag("travis.png", size: "90x30") %>
  </a>
  <div class="collapse navbar-collapse">
    <div class="navbar-nav">
      <%= link_to 'Home', repositories_path, class: 'nav-item nav-link active' %>
      <a class="nav-item nav-link" href="#">Statistics</a>
      <a class="nav-item nav-link" href="https://github.com">Github</a>
    </div>
  </div>
  <%= form_tag(repositories_path, method: "get", class: 'form-inline') do %>
    <%= search_field_tag :search_text, nil, {class: 'form-control mr-sm-2', placeholder: "Repo Id/Name", 'aria-label': "Search"} %>
    <%= button_tag 'Search', class: 'btn btn-outline-success my-2 my-sm-0' %>
  <% end %>
</nav>

<div class="container">
  <% @repo.each do |repo| %>
    <div class="row border rounded my-2 py-2  <%= repo.has_compiler_error == 1 ? "border-warning bg-info text-white" : "border-info bg-light" %>">
      <div class="col-2">
        <%= repo.id %>
      </div>
      <div class="col-6 text-center">
        <% link_color = repo.has_compiler_error == 1 ? "text-light" : "text-dark" %>
        <%= link_to repo.repo_name, repository_jobs_path(repo), target: "_blank", class: link_color %>
      </div>
      <div class="col-2">
        Star <%= repo.stars %>
      </div>
      <div class="col-2">
        Build <%= repo.builds %>
      </div>
    </div>
  <% end %>
</div>

<div class="container">
  <div class="row justify-content-center">
    <div class="col-auto">
      <%= will_paginate @repo %> 
    </div>
  </div>
</div>

app/views/repositories/jobs.html.erb
<h1>Jobs</h1>
<table>
  <tr>
    <th>Number</th>
    <th>State</th>
    <th>Branch</th>
    <th>Compare Url</th>
    <th>Log</th>
    <th>Message</th>
  </tr>
  <% @jobs.each do |job| %>
    <tr>
      <td><%= job.job_number %></td>
      <td><%= job.job_state %></td>
      <td><%= link_to job.build_branch, "/repository/jobs?repo_id=#{job.travis_java_repository_id}&branch=#{job.build_branch}" %></td>
      <td><%= link_to nil, job.commit_compare_url %></td>
      <td><%= link_to 'log', "/repository/log?repo=#{job.repo_name}&job_number=#{job.job_number}" %></td>
      <td><%= job.commit_message %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @jobs, :inner_window => 10 %>

app/views/repository/index.html.erb
<h1>Scanning Repositories List</h1>
<%= form_tag("/repository/index", method: "get") do %>
  <%= label_tag(:repo_name, "Repo: ") %>
  <%= text_field_tag(:repo_name) %>
  <%= label_tag(:builds, "Builds: ") %>
  <%= text_field_tag(:builds) %>
  <%= label_tag(:stars, "Stars: ") %>
  <%= text_field_tag(:stars) %>
  <%= submit_tag("Search") %>
<% end %>
<table>
  <tr>
    <th>ID</th>
    <th>Repo_name</th>
    <th>Stras</th>
    <th>Builds</th>
  </tr>
  <% @repo.each do |repo| %>
    <tr>
      <td><%= repo.id %></td>
      <td><%= link_to repo.repo_name, "/repository/jobs?repo_id=#{repo.id}" %></td>
      <td><%= repo.stars %></td>
      <td><%= repo.builds %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @repo %>